### ISSUE TITLE
"Unsupported architecture" exception on Raspberry Pi

### ISSUE THREAD

**Issue by rdlauer** [edgeimpulse/edge-impulse-cli#14]
Trying to execute the following command on a Raspberry Pi...

`edge-impulse-linux-runner --download modelfile.eim`

...results in an "unsupported architecture" error that seems to contradict itself:

```
[RUN] Failed to run impulse Error: Unsupported architecture "aarch64", only armv7l or aarch64 supported for now
    at RunnerDownloader.getDownloadType (/usr/lib/node_modules/edge-impulse-linux/build/cli/linux/runner-downloader.js:31:27)
    at async RunnerDownloader.getLastDeploymentVersion (/usr/lib/node_modules/edge-impulse-linux/build/cli/linux/runner-downloader.js:55:28)
    at async /usr/lib/node_modules/edge-impulse-linux/build/cli/linux/runner.js:123:31
```

**Comment by janjongboom** [comment]
Hi @rdlauer on the forum people have seen this with 64-bit Raspbian, switching to 32-bit should work fine. We're investigating.

**Comment by mmajchrzycki** [comment]
This is resolved now.
